#!/usr/bin/env bash
set -euo pipefail

# QNX Boost cross-build script.
#
# Builds Boost using the direct ntoaarch64-g++ GCC cross-compiler.
#
# Notes:
#   - b2 5.x segfaults with 'target-os=qnxnto' when using the qcc toolset
#     (known upstream bug). We use the direct ntoaarch64-g++ GCC cross-compiler
#     with the 'gcc' toolset instead, which avoids the segfault.
#   - bootstrap.sh generates project-config.jam that configures the host gcc;
#     we remove it before running b2 so user-config.jam takes precedence.
#   - MAKEFLAGS from qnxsdp-env.sh (-I/path/to/qnx/usr/include) must be
#     cleared so it does not pollute b2's internal make invocations.
#
# Usage:
#   ./qnx/scripts/build_boost_qnx.sh install --arch aarch64le
#   ./qnx/scripts/build_boost_qnx.sh clean

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

ACTION="build"
if [[ $# -gt 0 ]] && [[ "$1" != --* ]]; then
  ACTION="$1"
  shift
fi

ARCH="$(qnx_default_arch)"
OUT_ROOT="$(qnx_default_out_root)"
JOBS="$(qnx_default_jobs)"
BOOST_VERSION="1.86.0"
INSTALL_PREFIX="${OUT_ROOT}/third_party"
WORK_DIR="${AUTOSAR_QNX_WORK_ROOT:-${REPO_ROOT}/out/qnx/work}/boost/${ARCH}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --arch)
      ARCH="$2"; shift 2;;
    --prefix)
      INSTALL_PREFIX="$2"; shift 2;;
    --work-dir)
      WORK_DIR="$2"; shift 2;;
    --jobs)
      JOBS="$2"; shift 2;;
    --version)
      BOOST_VERSION="$2"; shift 2;;
    *)
      qnx_error "Unknown argument: $1"; exit 1;;
  esac
done

qnx_setup_env
qnx_require_cmd "tar"

QCC_VARIANT="$(qnx_arch_to_qcc_variant "${ARCH}")"
# Use direct GCC cross-compiler (avoids b2 5.x segfault with qcc+target-os=qnxnto).
# The compiler binary uses the base arch name without endian suffix (e.g. ntoaarch64-g++,
# not ntoaarch64le-g++).
NTO_ARCH="${ARCH%le}"   # strip trailing 'le': aarch64le -> aarch64
NTO_ARCH="${NTO_ARCH%be}" # strip trailing 'be': aarch64be -> aarch64
NTOCXX="$(command -v "nto${NTO_ARCH}-g++" 2>/dev/null || true)"
if [[ -z "${NTOCXX}" ]]; then
  qnx_error "nto${NTO_ARCH}-g++ not found in PATH. Source qnxsdp-env.sh first."
  exit 1
fi

BOOST_VERSION_U="${BOOST_VERSION//./_}"
BOOST_ARCHIVE="boost_${BOOST_VERSION_U}.tar.gz"
BOOST_URL="https://archives.boost.io/release/${BOOST_VERSION}/source/${BOOST_ARCHIVE}"
SOURCE_DIR="${WORK_DIR}/boost_${BOOST_VERSION_U}"
ARCHIVE_PATH="${WORK_DIR}/${BOOST_ARCHIVE}"

if [[ "${ACTION}" == "clean" ]]; then
  rm -rf "${WORK_DIR}"
  qnx_info "Cleaned ${WORK_DIR}"
  exit 0
fi

mkdir -p "${WORK_DIR}"
mkdir -p "${INSTALL_PREFIX}"
chmod 777 "${INSTALL_PREFIX}"

qnx_info "Build Boost for QNX (static, toolset=gcc-ntoaarch64)"
qnx_info "  version=${BOOST_VERSION} arch=${ARCH} variant=${QCC_VARIANT}"
qnx_info "  prefix=${INSTALL_PREFIX} work_dir=${WORK_DIR}"
qnx_info "  cxx=${NTOCXX}"

# Download & extract
if [[ ! -f "${ARCHIVE_PATH}" ]]; then
  qnx_download_file "${BOOST_URL}" "${ARCHIVE_PATH}"
fi
rm -rf "${SOURCE_DIR}"
tar -xzf "${ARCHIVE_PATH}" -C "${WORK_DIR}"

pushd "${SOURCE_DIR}" >/dev/null

# Create user-config.jam pointing to the QNX AArch64 GCC cross-compiler.
# We use the 'gcc' toolset with variant name matching the QNX tuple so that
# b2 can find it as 'toolset=gcc-ntoaarch64'.
cat > user-config.jam <<CFG
using gcc
  : ntoaarch64
  : ${NTOCXX}
  : <cxxflags>"-D_QNX_SOURCE -fPIC"
  ;
CFG

./bootstrap.sh

# Remove project-config.jam generated by bootstrap so it does not override
# our user-config.jam (bootstrap detects and configures the host gcc).
rm -f project-config.jam

# MAKEFLAGS from qnxsdp-env.sh (-I.../usr/include) must be cleared so it
# does not pollute b2's internal make invocations on the host.
unset MAKEFLAGS

./b2 install \
  --user-config=./user-config.jam \
  toolset=gcc-ntoaarch64 \
  variant=release \
  link=static \
  target-os=qnxnto \
  architecture=arm \
  address-model=64 \
  --prefix="${INSTALL_PREFIX}" \
  --with-system --with-thread --with-filesystem \
  --with-program_options --with-chrono --with-atomic --with-date_time \
  -j"${JOBS}"

popd >/dev/null

qnx_info "Boost installation complete: ${INSTALL_PREFIX}"
