#ifndef CRYPTO_PROVIDER_H
#define CRYPTO_PROVIDER_H

#include <cstddef>
#include <cstdint>
#include <vector>
#include "../core/result.h"
#include "./crypto_error_domain.h"

namespace ara
{
    namespace crypto
    {
        /// @brief Digest algorithms supported by this ara::crypto subset.
        enum class DigestAlgorithm : std::uint32_t
        {
            kSha1 = 0,      ///< SHA-1 (160-bit)
            kSha256 = 1,     ///< SHA-256 (256-bit)
            kSha384 = 2,     ///< SHA-384 (384-bit)
            kSha512 = 3      ///< SHA-512 (512-bit)
        };

        /// @brief Compute a digest for the provided input bytes.
        /// @param data Input bytes.
        /// @param algorithm Digest algorithm.
        /// @returns Digest bytes or a crypto domain error.
        core::Result<std::vector<std::uint8_t>> ComputeDigest(
            const std::vector<std::uint8_t> &data,
            DigestAlgorithm algorithm = DigestAlgorithm::kSha256);

        /// @brief Generate cryptographically strong random bytes.
        /// @param byteCount Number of bytes to generate.
        /// @returns Generated bytes or a crypto domain error.
        core::Result<std::vector<std::uint8_t>> GenerateRandomBytes(
            std::size_t byteCount);

        /// @brief Compute HMAC for provided data using a symmetric key.
        /// @param data Input bytes.
        /// @param key HMAC key bytes (must not be empty).
        /// @param algorithm Digest algorithm used for the HMAC.
        /// @returns HMAC bytes or a crypto domain error.
        core::Result<std::vector<std::uint8_t>> ComputeHmac(
            const std::vector<std::uint8_t> &data,
            const std::vector<std::uint8_t> &key,
            DigestAlgorithm algorithm = DigestAlgorithm::kSha256);

        /// @brief Generate a symmetric key of the given byte length.
        /// @param keyLengthBytes Key length in bytes (16 for AES-128, 32 for AES-256).
        /// @returns Generated key bytes or a crypto domain error.
        core::Result<std::vector<std::uint8_t>> GenerateSymmetricKey(
            std::size_t keyLengthBytes);

        /// @brief Encrypt plaintext using AES-CBC with PKCS#7 padding.
        /// @param plaintext Input data.
        /// @param key AES key (16 bytes for AES-128 or 32 bytes for AES-256).
        /// @param iv Initialization vector (must be 16 bytes).
        /// @returns Ciphertext bytes or a crypto domain error.
        core::Result<std::vector<std::uint8_t>> AesEncrypt(
            const std::vector<std::uint8_t> &plaintext,
            const std::vector<std::uint8_t> &key,
            const std::vector<std::uint8_t> &iv);

        /// @brief Decrypt ciphertext using AES-CBC with PKCS#7 padding removal.
        /// @param ciphertext Encrypted data.
        /// @param key AES key (16 bytes for AES-128 or 32 bytes for AES-256).
        /// @param iv Initialization vector (must be 16 bytes).
        /// @returns Plaintext bytes or a crypto domain error.
        core::Result<std::vector<std::uint8_t>> AesDecrypt(
            const std::vector<std::uint8_t> &ciphertext,
            const std::vector<std::uint8_t> &key,
            const std::vector<std::uint8_t> &iv);
    }
}

#endif
