#ifndef CRYPTO_PROVIDER_H
#define CRYPTO_PROVIDER_H

#include <cstddef>
#include <cstdint>
#include <vector>
#include "../core/result.h"
#include "./crypto_error_domain.h"

namespace ara
{
    namespace crypto
    {
        /// @brief Digest algorithms supported by this ara::crypto subset.
        enum class DigestAlgorithm : std::uint32_t
        {
            kSha256 = 1
        };

        /// @brief Compute a digest for the provided input bytes.
        /// @param data Input bytes.
        /// @param algorithm Digest algorithm.
        /// @returns Digest bytes or a crypto domain error.
        core::Result<std::vector<std::uint8_t>> ComputeDigest(
            const std::vector<std::uint8_t> &data,
            DigestAlgorithm algorithm = DigestAlgorithm::kSha256);

        /// @brief Generate cryptographically strong random bytes.
        /// @param byteCount Number of bytes to generate.
        /// @returns Generated bytes or a crypto domain error.
        core::Result<std::vector<std::uint8_t>> GenerateRandomBytes(
            std::size_t byteCount);
    }
}

#endif
